import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" h-screen">
      <body className={`${inter.className} h-full  w-screen` }>
        <AuthProvider>
          <Header/>
          <div className="flex items-center justify-center flex-col min-h-[92%] ">{children}</div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
