import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { ThemeProvider } from "@/context/theme-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LMS",
  description: "Generated by create next app",
  head: (
    <>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Delius&family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');
</style>
    </>
  ),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/logo.jpeg" sizes="any" />
      <body className={`${inter.className}  overflow-x-hidden `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <AuthProvider>
          <SidebarProvider defaultOpen={false} >
            <AppSidebar />
              <main className=" w-full min-h-screen flex flex-col   bg-gray-100  dark:bg-gray-800">

              <Header/>
              
                  {children}
              
            </main>
          </SidebarProvider>
          

          <Toaster />
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
