import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { ThemeProvider } from "@/context/theme-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/logo.jpeg" sizes="any" />
      <body className={`${inter.className} h-screen overflow-x-hidden `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <AuthProvider>
          <SidebarProvider defaultOpen={false} >
            <AppSidebar />
            <main className=" w-full bg-gray-100 ">

              <Header/>
              {children}
            </main>
          </SidebarProvider>
          

          <Toaster />
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
